### ISSUE TITLE
Error in Gemma Neo Pixels program

### ISSUE THREAD

**Issue by LedArts** [cameraready/Gemma_NeoPixels#1]
hello sir, plz help me.
When i try your code and compile first time this error occur what should u do plz tell me.

Arduino: 1.8.0 (Windows 7), Board: "Arduino/Genuino Uno"

C:\Program Files\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\Arduino\hardware -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files\Arduino\libraries -libraries D:\Arduino Sketches\libraries -fqbn=arduino:avr:uno -ide-version=10800 -build-path C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -verbose D:\Arduino Sketches\NeoPixelFirewalk\NeoPixelFirewalk.ino
C:\Program Files\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files\Arduino\hardware -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files\Arduino\libraries -libraries D:\Arduino Sketches\libraries -fqbn=arduino:avr:uno -ide-version=10800 -build-path C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -verbose D:\Arduino Sketches\NeoPixelFirewalk\NeoPixelFirewalk.ino
Using board 'uno' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Detecting libraries used...
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\sketch\NeoPixelFirewalk.ino.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Program Files\Arduino\libraries\Adafruit_NeoPixel" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\sketch\NeoPixelFirewalk.ino.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Program Files\Arduino\libraries\Adafruit_NeoPixel" "C:\Program Files\Arduino\libraries\Adafruit_NeoPixel\Adafruit_NeoPixel.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Program Files\Arduino\libraries\Adafruit_NeoPixel" "C:\Program Files\Arduino\libraries\Adafruit_NeoPixel\esp8266.c" -o "nul"
Generating function prototypes...
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Program Files\Arduino\libraries\Adafruit_NeoPixel" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\sketch\NeoPixelFirewalk.ino.cpp" -o "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Program Files\Arduino\libraries\Adafruit_NeoPixel" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\sketch\NeoPixelFirewalk.ino.cpp" -o "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\sketch\NeoPixelFirewalk.ino.cpp.o"
In file included from C:\Program Files\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:28:0,

                 from C:\Users\Pankaj\AppData\Local\Temp\arduino_build_751000\sketch\NeoPixelFirewalk.ino.cpp:1:

NeoPixelFirewalk:6: error: variable 'gamma' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 uint8_t gamma[] PROGMEM = { // Gamma correction table for LED brightness

                 ^

Using library Adafruit_NeoPixel at version 1.0.6 in folder: C:\Program Files\Arduino\libraries\Adafruit_NeoPixel 
exit status 1
variable 'gamma' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

**Comment by cameraready** [comment]
I've updated the code by adding 'const' to the gamma[] var on line 6. That should allow it to compile on newer versions of the Arduino IDE.
